### ISSUE TITLE
Pet Protection Issue

### ISSUE THREAD

**Issue by PandaTDG** [bloodmc/GriefDefenderDoc#25]
I am unsure if this is the correct place to mention an issue, or ask for help, but it is the only place I could find for support.  After extensively reading the wiki, and other in-game tools, I have been unable to resolve an ongoing issue.  I am attempting to disable the pet protection of certain players pets, however no claim flag, debug tools, or settings appear to help; unless the pet is owned by the player interacting with it.  I would appreciate any help.

**Comment by bloodmc** [comment]
This repo is reserved for docs only. If you need support, you should be asking on GD's discord.
